### ISSUE TITLE
What if catframes failed to start or it crashed or it was not found

### ISSUE THREAD

**Issue by georgy7** [georgy7/catframes#28]
This is not how the subprocess should be started.

1. You should not use `shell=True`. You get too attached to the platform. And it may cause security problems. You also get the terminal's PID instead of PID of the script.
2. You should check that the process has started and it is still running. If this is not the case, you need to let the user know about it, because this may indicate problems with the installation. For example, catframes will crash if FFmpeg is not installed. A message about this is displayed in `stderr`.

**Comment by NeiroSlav** [comment]
1. The startup process no longer has a shell. Now it has different initial parameters on startup, depending on the OS. This allows the entire process tree termination.
2. Missing catframes or ffmpeg script, process start fail and process runtime errors will be handled, and thrown to the GUI layer.

**Comment by georgy7** [comment]
The file is ready, ffmpeg and catframes have completed, but the task is supposedly not completed.
The progress is displayed as 0%.

![2eqawqeq](https://github.com/user-attachments/assets/363e019f-4277-4586-a0ca-8ae091c7dcdd)
