### ISSUE TITLE
Strange behavior of the Cancel button

### ISSUE THREAD

**Issue by georgy7** [georgy7/catframes#29]
The Cancel button hides a task **without any clarifying question.**

In addition, FFmpeg process continues to run in task manager.

Commit: d7ceb6f4b2648b1b5d2ca92ca2458a37238d5fcc
Platform: Win10 Pro.
Catframes is installed from pip.

-------

By the way, if the program had asked before canceling the task, it would have been possible to replace this huge button with an icon. Confusion between the Cancel and Delete buttons can be avoided if you don't do the Delete button at all. Why delete tasks from the list if they are not saved when the program is closed? Although this is not so important.

**Comment by NeiroSlav** [comment]
Done

**Comment by georgy7** [comment]
>clarifying question

**Are you sure, you want to cancel creating "blabla.mp4"?
Yes / No**
