### ISSUE TITLE
Line feeds in overlays

### ISSUE THREAD

**Issue by georgy7** [georgy7/catframes#31]
There is no way to put a newline in the overlay (neither Enter, Ctrl+Enter, nor Alt+Enter have any effect).

Expected behavior:
Pressing one of the above keyboard shortcuts will add a newline to the place in the overlay where the text cursor is currently located. This line feed will turn into an escape sequence in the resulting console command.

**Comment by georgy7** [comment]
If a key combination will be used instead of Enter, then Enter should finish editing the overlay or something like that. At the moment, nothing happens when you press it.

**Comment by NeiroSlav** [comment]
Pressing Enter will add a newline. 
Pressing Escape will hide input field.
Overlay text lines alignment to border side (for example, if you type text in right field, its pure text will be right aligned)

May improve in the future:
- vertical field movement. When entering text in the upper field, when the line is translated, the field will move down. And in the lower field - move up. This will prevent the input field from going beyond the canvas.
- automatic field width stretching. Initially, the field will appear small, and if one of the lines exceeds this size, the field will stretch in width. This will allow you to initially display a more compact field, but enter a lot of text if necessary.

**Comment by georgy7** [comment]
>vertical field movement

Regardless of the implementation mechanism, the lower margins should feel as if they are aligned at the bottom edge (last line is visible), and the upper ones as if they are aligned at the top edge (first line is visible).

**Comment by georgy7** [comment]
Almost done. It has issues with horizontal alignment.
