### ISSUE TITLE
New Task Window Improvements

### ISSUE THREAD

**Issue by georgy7** [georgy7/catframes#32]
1. Create button is not highlighted as the main button of the form. It should have a special [ttk style](https://docs.python.org/3/library/tkinter.ttk.html#ttkstyling) (something like [btn-primary](https://getbootstrap.com/docs/5.0/components/buttons/) in Twitter Bootstrap CSS framework).

2. Create button should be anchored to the lower right corner of the window, regardless of what the layout will be. These margins indicate incorrect layout.

![bad_footer_layout](https://github.com/user-attachments/assets/91d581a6-4528-4550-8ea6-a2184c039a5c)

3. The most informative parts of the form do not fill the available space.

![expand_list](https://github.com/user-attachments/assets/435f5d36-39a1-4e76-b7b5-93c9346da35b)

4. You should reduce the amount of background computation on this form. You don't need to calculate the final resolution of the video when you add a folder. Also, it is _enough_ to take 3-4 random frames for preview and show them them in loop. You don't need to show entire video in the preview in this form. Also, it is better to switch frames in the preview no more than once every 5 seconds (this distracts). Although, to be honest, it would be less surprising if there was a transition through translucency between these frames.

5. I recommend using PannedWindow to allow users to resize the preview along two axes. This way you can work more efficiently with the form on small screens. In addition, the aspect ratio of the canvas will generally not be equal to the aspect ratio of the video frame. Thus, the users will be able to see the background of the video on the sides of the canvas, the color of which they set through the interface.

6. The target video file must be listed on the form, not when you click Create.

7. It is better to change the default background to black, and the quality to medium.

**Comment by NeiroSlav** [comment]
directory*
My spelling is divine

**Comment by NeiroSlav** [comment]
Done

**Comment by georgy7** [comment]
About the second point:

![qweqwe2](https://github.com/user-attachments/assets/00f4691c-de54-4b97-9f4b-4ffa07e8f18f)
